# Generated by Django 5.1.2 on 2024-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('purchase_time', models.DateTimeField(blank=True, null=True)),
                ('allowed_courses', models.ManyToManyField(blank=True, to='lessons.lesson')),
            ],
        ),
    ]
