# Generated by Django 5.1.3 on 2024-11-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botusers", "0001_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botuser",
            name="allowed_courses",
            field=models.ManyToManyField(
                blank=True, to="lessons.lesson", verbose_name="Ruxsat etilgan kurslar"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="is_purchased",
            field=models.BooleanField(default=False, verbose_name="Sotib olinganmi?"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Foydalanuvchi ismi"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefon raqami"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="purchase_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sotib olish vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.BigIntegerField(
                primary_key=True,
                serialize=False,
                verbose_name="Telegram foydalanuvchi ID",
            ),
        ),
    ]
