# Generated by Django 5.1.2 on 2024-11-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botusers', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.CharField(choices=[('tekshirilmoqda', 'Tekshirilmoqda'), ('muvaffaqiyatli', 'Muvaffaqiyatli'), ('muvaffaqiyatsiz', 'Muvaffaqiyatsiz')], default='tekshirilmoqda', max_length=122)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botusers.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.URLField(max_length=250)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworks')),
            ],
        ),
    ]
