# Generated by Django 5.1.3 on 2024-11-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botusers", "0002_alter_botuser_allowed_courses_and_more"),
        ("homeworks", "0001_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkfiles",
            name="file_id",
            field=models.URLField(max_length=250, verbose_name="Fayl ID"),
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuborilgan vaqt"
                    ),
                ),
                (
                    "is_successful",
                    models.CharField(
                        choices=[
                            ("tekshirilmoqda", "Tekshirilmoqda"),
                            ("muvaffaqiyatli", "Muvaffaqiyatli"),
                            ("muvaffaqiyatsiz", "Muvaffaqiyatsiz"),
                        ],
                        default="tekshirilmoqda",
                        max_length=122,
                        verbose_name="Natija",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.lesson",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botusers.botuser",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="homeworkfiles",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="homeworks.homework",
                verbose_name="Uy vazifasi",
            ),
        ),
        migrations.DeleteModel(
            name="Homeworks",
        ),
    ]
